import LegalPage from "../components/content/LegalPage"

const sections = [
  { title: "Information we collect", paragraphs: ["GeekOnSites, a service by ASI TECH INC, collects information you provide when creating an account, requesting support, booking a service, making a payment, contacting us, or leaving a review."], items: ["Account and contact details, including name, email address, phone number, country, and service address.", "Booking details, device or issue information, selected services, appointment preferences, support messages, and service history.", "Transaction references and payment status. Complete card details are handled by the payment provider and are not intended to be stored by GeekOnSites.", "Technical information such as device, browser, app version, IP address, diagnostics, and approximate location when necessary and permitted."] },
  { title: "How we use information", items: ["Create and secure accounts, process bookings, take payments, and provide remote or on-site support.", "Assign technicians, communicate service updates, provide invoices, respond to support requests, and manage complaints or refunds.", "Detect fraud, protect customers and technicians, maintain platform security, and meet legal obligations.", "Improve service quality, availability, pricing, and the customer experience."] },
  { title: "When information is shared", paragraphs: ["We share information only when needed to operate the service, complete a booking, protect users, or comply with law."], items: ["Assigned technicians and authorised support personnel receive the details needed to deliver the requested service.", "Payment, hosting, communications, analytics, and security providers may process limited information on our behalf.", "Information may be disclosed to regulators, courts, law enforcement, insurers, or professional advisers where legally required or reasonably necessary.", "We do not sell personal information for money."] },
  { title: "Remote access and location", paragraphs: ["Remote access occurs only when you choose a remote service and grant permission through the approved session tool. You can end the session at any time. On-site tracking or precise location is used only when enabled for booking fulfilment, safety, or technician arrival updates."] },
  { title: "Retention and security", paragraphs: ["We retain information for as long as reasonably necessary to provide services, maintain transaction and service records, resolve disputes, prevent fraud, and meet tax, accounting, or legal duties. We use administrative, technical, and organisational safeguards, but no online system can guarantee absolute security."] },
  { title: "Your choices and rights", paragraphs: ["Depending on where you live, you may request access, correction, deletion, restriction, portability, or objection to certain processing. You may also withdraw optional permissions through your device or browser settings. Some records must be retained where required by law or needed to establish or defend legal claims."], items: ["Submit a request through the Support page using the email connected to your account.", "You may complain to the relevant privacy or data-protection authority in your jurisdiction.", "GeekOnSites services are not directed to children under 18, and we do not knowingly create accounts for them."] },
  { title: "Updates and contact", paragraphs: ["We may update this policy when our services or legal requirements change. Material updates will be identified by a revised effective date and, where appropriate, an in-app or email notice.", "Privacy questions and requests can be submitted through the GeekOnSites Support page or sent to support@geekonsites.com."] },
]

export default function PrivacyPolicy() {
  return <LegalPage eyebrow="Legal and privacy" title="Privacy Policy" description="How GeekOnSites collects, uses, shares, and protects information across our website, app, remote support, and on-site services." sections={sections} seoTitle="Privacy Policy | GeekOnSites" />
}
