import LegalPage from "../components/content/LegalPage"

const sections = [
  { title: "Agreement and service operator", paragraphs: ["These Terms & Conditions apply when you access GeekOnSites or book a remote or on-site service. GeekOnSites is a service by ASI TECH INC. By creating an account, placing a booking, or accepting service, you agree to these terms and the Privacy Policy."] },
  { title: "Accounts and eligibility", items: ["You must be at least 18 years old and legally able to enter into a contract.", "Account, contact, device, and booking information must be accurate and kept current.", "You are responsible for protecting your login credentials and notifying us promptly of suspected unauthorised access.", "We may restrict or suspend accounts used fraudulently, unlawfully, abusively, or in a way that threatens platform safety."] },
  { title: "Bookings and service delivery", items: ["A booking is accepted only after the platform confirms it. Technician availability and arrival estimates are not guarantees.", "Remote service requires a compatible device, working internet connection, and your express permission to start the session.", "On-site service requires safe and reasonable access to the service location, device, network, and an authorised adult contact.", "A technician may stop or decline work that is unsafe, unlawful, outside the booked scope, or requires unavailable parts or specialist facilities."] },
  { title: "Pricing, payments, and additional work", paragraphs: ["Prices, taxes, call-out charges, deposits, and included work are shown before checkout where available. Charges for parts, additional time, or work outside the original scope must be presented for approval before they are added. Payment authorisation may be required before a booking is confirmed or completed."], items: ["Currency and regional pricing depend on the selected US or UK service region.", "You are responsible for authorised charges and any accurately disclosed taxes or regulatory fees.", "Invoices and payment status are made available through the applicable account or booking flow."] },
  { title: "Cancellations, rescheduling, and refunds", paragraphs: ["Cancellation, rescheduling, no-access, diagnostic, and refund eligibility may depend on the service type, technician dispatch status, work already completed, parts ordered, and applicable consumer law. Any specific policy and charge shown during booking forms part of these terms. Nothing in these terms removes mandatory consumer rights that cannot lawfully be excluded."] },
  { title: "Customer responsibilities", items: ["Back up important data before support begins and disclose known device, access, safety, or security issues.", "Do not share passwords or payment credentials in support messages. Enter credentials yourself where possible.", "Confirm that you own or are authorised to access the devices, accounts, software, premises, and networks involved.", "Maintain valid software licences and do not request circumvention of security, access controls, or applicable law."] },
  { title: "Parts, warranties, and service outcomes", paragraphs: ["Replacement parts and third-party products may carry their manufacturer's warranty. Service outcomes depend on device condition, prior damage, available parts, connectivity, software support, and customer access. We do not promise that every issue can be repaired or that data can always be recovered. Any specific GOS workmanship commitment stated in writing applies alongside your mandatory legal rights."] },
  { title: "Liability", paragraphs: ["To the maximum extent permitted by applicable law, GeekOnSites and ASI TECH INC are not responsible for indirect, incidental, special, or consequential loss, or loss caused by inaccurate customer information, pre-existing faults, unsupported systems, third-party products, malware, interrupted connectivity, or failure to maintain a reasonable backup. Nothing excludes liability that cannot legally be excluded, including applicable rights relating to fraud, personal injury, or consumer protection."] },
  { title: "Changes, law, and contact", paragraphs: ["We may update these terms as services or legal requirements change. The terms in effect when you place a booking apply to that booking unless a change is required by law or agreed with you. Applicable law and dispute rights depend on the contracting entity, service location, and mandatory rules in your jurisdiction.", "Questions, complaints, and legal notices may be submitted through the Support page or sent to support@geekonsites.com."] },
]

export default function TermsConditions() {
  return <LegalPage eyebrow="Service agreement" title="Terms & Conditions" description="The rules that apply when customers use GeekOnSites accounts, bookings, payments, remote sessions, and on-site technology services." sections={sections} seoTitle="Terms & Conditions | GeekOnSites" relatedLinks={[{ label: "Refund & Cancellation Policy", to: "/refund-policy" }, { label: "Privacy Policy", to: "/privacy" }]} />
}
