import { useCallback, useEffect, useState } from "react"
import { ArrowLeft, Check, ChevronLeft, ChevronRight, Search } from "lucide-react"
import { addCrmFollowUp, addCrmNote, completeCrmFollowUp, getCrmCustomer, getCrmCustomers, getCrmSummary } from "../../services/agentCrmService"

const field = "min-h-11 w-full rounded-xl border border-white/10 bg-[#071122] px-3 text-sm text-white outline-none focus:border-cyan-400/60"
const fmt = (value) => value ? new Date(value).toLocaleString() : "—"

export default function AgentCrm({ onOpenBooking, notify }) {
  const [filters, setFilters] = useState({ search: "", country: "", bookingStatus: "", serviceMode: "", followUpStatus: "", page: 0, size: 15 })
  const [page, setPage] = useState({ content: [], totalElements: 0, totalPages: 0, page: 0 })
  const [summary, setSummary] = useState(null)
  const [selected, setSelected] = useState(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [note, setNote] = useState("")
  const [followUp, setFollowUp] = useState({ followUpAt: "", reason: "", internalNote: "" })

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const [customers, totals] = await Promise.all([getCrmCustomers(filters), getCrmSummary()])
      setPage(customers); setSummary(totals)
    } catch (error) { notify(error.message || "CRM data could not be loaded") }
    finally { setLoading(false) }
  }, [filters, notify])

  useEffect(() => { const timer = setTimeout(load, filters.search ? 250 : 0); return () => clearTimeout(timer) }, [load, filters.search])
  const update = (key, value) => setFilters((current) => ({ ...current, [key]: value, page: 0 }))
  const openCustomer = async (id) => { setLoading(true); try { setSelected(await getCrmCustomer(id)) } catch (error) { notify(error.message) } finally { setLoading(false) } }
  const refreshDetail = async () => selected && setSelected(await getCrmCustomer(selected.id))
  const saveNote = async (event) => { event.preventDefault(); if (!note.trim() || saving) return; setSaving(true); try { await addCrmNote(selected.id, note); setNote(""); await refreshDetail(); notify("CRM note added") } catch (error) { notify(error.message) } finally { setSaving(false) } }
  const saveFollowUp = async (event) => { event.preventDefault(); if (saving) return; setSaving(true); try { await addCrmFollowUp(selected.id, followUp); setFollowUp({ followUpAt: "", reason: "", internalNote: "" }); await refreshDetail(); await load(); notify("Follow-up scheduled") } catch (error) { notify(error.message) } finally { setSaving(false) } }
  const complete = async (id) => { if (saving) return; setSaving(true); try { await completeCrmFollowUp(id); await refreshDetail(); await load(); notify("Follow-up completed") } catch (error) { notify(error.message) } finally { setSaving(false) } }

  if (selected) return <div className="space-y-5">
    <button onClick={() => setSelected(null)} className="inline-flex items-center gap-2 text-sm font-black text-cyan-300"><ArrowLeft size={16}/>Back to CRM customers</button>
    <section className="rounded-3xl border border-white/10 bg-[#0b1628] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-cyan-300">Customer GOS-C-{selected.id}</p><h2 className="mt-2 text-2xl font-black">{selected.name}</h2><p className="mt-1 text-sm text-cyan-100/60">{selected.email} · {selected.phone || "No phone"} · {selected.country || "—"}</p></div><p className="max-w-md text-sm text-cyan-100/60">{selected.address || "No authorized service address recorded"}</p></div></section>
    <div className="grid gap-5 xl:grid-cols-2">
      <section className="rounded-3xl border border-white/10 bg-[#0b1628] p-5"><h3 className="font-black">Booking history</h3><div className="mt-4 space-y-3">{selected.bookings.length ? selected.bookings.map((b) => <button key={b.id} onClick={() => onOpenBooking?.(b.id)} className="w-full rounded-2xl border border-white/10 bg-[#071122] p-4 text-left hover:border-cyan-400/40"><div className="flex justify-between gap-3"><b>GOS-{b.id} · {b.service}</b><span className="text-xs text-cyan-300">{b.status}</span></div><p className="mt-2 text-xs text-cyan-100/55">{b.serviceMode} · {b.date || "—"} · {b.technician || "Unassigned"} · {b.paymentStatus}</p></button>) : <p className="text-sm text-cyan-100/50">No bookings recorded.</p>}</div></section>
      <section className="rounded-3xl border border-white/10 bg-[#0b1628] p-5"><h3 className="font-black">Contact history</h3><div className="mt-4 space-y-3">{selected.enquiries.length ? selected.enquiries.map((e) => <article key={e.id} className="rounded-2xl border border-white/10 bg-[#071122] p-4"><div className="flex justify-between gap-3"><b>{e.subject}</b><span className="text-xs text-cyan-300">{e.status}</span></div><p className="mt-2 text-sm text-cyan-100/60">{e.message}</p><p className="mt-2 text-xs text-cyan-100/40">{fmt(e.createdAt)}</p></article>) : <p className="text-sm text-cyan-100/50">No linked enquiries.</p>}</div></section>
    </div>
    <div className="grid gap-5 xl:grid-cols-2">
      <section className="rounded-3xl border border-white/10 bg-[#0b1628] p-5"><h3 className="font-black">Internal notes</h3><form onSubmit={saveNote} className="mt-4 flex gap-2"><textarea aria-label="Internal CRM note" maxLength={4000} value={note} onChange={(e)=>setNote(e.target.value)} className={`${field} min-h-24 flex-1 py-3`} placeholder="Add an internal note…"/><button disabled={saving || !note.trim()} className="self-end rounded-xl bg-cyan-400 px-4 py-3 text-sm font-black text-[#061326] disabled:opacity-50">Add</button></form><div className="mt-4 space-y-3">{selected.notes.map((n)=><article key={n.id} className="rounded-2xl border border-white/10 bg-[#071122] p-4"><p className="text-sm text-cyan-50">{n.noteText}</p><p className="mt-2 text-xs text-cyan-100/40">{n.authorName} · {fmt(n.createdAt)}</p></article>)}</div></section>
      <section className="rounded-3xl border border-white/10 bg-[#0b1628] p-5"><h3 className="font-black">Follow-ups</h3><form onSubmit={saveFollowUp} className="mt-4 grid gap-2 sm:grid-cols-2"><input aria-label="Follow-up date and time" required type="datetime-local" value={followUp.followUpAt} onChange={(e)=>setFollowUp({...followUp,followUpAt:e.target.value})} className={field}/><input aria-label="Follow-up reason" required maxLength={250} value={followUp.reason} onChange={(e)=>setFollowUp({...followUp,reason:e.target.value})} className={field} placeholder="Reason"/><input aria-label="Optional internal note" maxLength={2000} value={followUp.internalNote} onChange={(e)=>setFollowUp({...followUp,internalNote:e.target.value})} className={`${field} sm:col-span-2`} placeholder="Optional internal note"/><button disabled={saving} className="rounded-xl bg-cyan-400 px-4 py-3 text-sm font-black text-[#061326] disabled:opacity-50">Schedule follow-up</button></form><div className="mt-4 space-y-3">{selected.followUps.map((f)=><article key={f.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/10 bg-[#071122] p-4"><div><b>{f.reason}</b><p className="mt-1 text-xs text-cyan-100/50">{fmt(f.followUpAt)} · {f.timing}</p></div>{f.status === "PENDING" && <button disabled={saving} onClick={()=>complete(f.id)} className="inline-flex items-center gap-2 rounded-xl border border-emerald-400/30 px-3 py-2 text-xs font-black text-emerald-300 disabled:opacity-50"><Check size={14}/>Complete</button>}</article>)}</div></section>
    </div>
  </div>

  const cards = summary ? [["Active customers",summary.totalActiveCustomers],["Open enquiries",summary.openEnquiries],["Active bookings",summary.activeBookings],["Due today",summary.followUpsDueToday],["Overdue",summary.overdueFollowUps]] : []
  return <div className="space-y-5"><div><p className="text-xs font-black uppercase tracking-[.22em] text-cyan-300">Customer operations</p><h2 className="mt-2 text-2xl font-black">CRM</h2><p className="mt-1 text-sm text-cyan-100/55">Customers, enquiries, bookings and follow-ups in one secure workspace.</p></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{cards.map(([label,value])=><div key={label} className="rounded-2xl border border-white/10 bg-[#0b1628] p-4"><p className="text-2xl font-black text-cyan-200">{value}</p><p className="mt-1 text-xs font-bold text-cyan-100/45">{label}</p></div>)}</div>
    <section className="rounded-3xl border border-white/10 bg-[#0b1628] p-4 sm:p-5"><div className="grid gap-2 md:grid-cols-6"><label className="relative md:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-cyan-100/35"/><input aria-label="Search customers" value={filters.search} onChange={(e)=>update("search",e.target.value)} className={`${field} pl-10`} placeholder="Search name, email or phone"/></label>{[["country","All countries",["US","UK"]],["bookingStatus","All booking statuses",["PENDING","TECHNICIAN_ASSIGNED","SERVICE_STARTED","SERVICE_COMPLETED","CANCELLED"]],["serviceMode","All service modes",["REMOTE","ONSITE"]],["followUpStatus","All follow-ups",["DUE_TODAY","UPCOMING","OVERDUE","NONE"]]].map(([key,label,values])=><select aria-label={label} key={key} value={filters[key]} onChange={(e)=>update(key,e.target.value)} className={field}><option value="">{label}</option>{values.map(v=><option key={v}>{v}</option>)}</select>)}</div>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-cyan-100/40"><tr>{["Customer","Country","Bookings","Latest booking","Mode / Technician","Payment","Follow-up"].map(h=><th key={h} className="border-b border-white/10 px-3 py-3">{h}</th>)}</tr></thead><tbody>{page.content.map((c)=><tr key={c.id} onClick={()=>openCustomer(c.id)} className="cursor-pointer border-b border-white/5 hover:bg-cyan-400/5"><td className="px-3 py-4"><b>{c.name}</b><p className="text-xs text-cyan-100/45">{c.email} · {c.phone || "No phone"}</p></td><td className="px-3 py-4">{c.country}</td><td className="px-3 py-4">{c.bookingCount}</td><td className="px-3 py-4">{c.latestBookingStatus || "—"}<p className="text-xs text-cyan-100/40">{fmt(c.latestBookingDate)}</p></td><td className="px-3 py-4">{c.serviceMode || "—"}<p className="text-xs text-cyan-100/40">{c.assignedTechnician || "Unassigned"}</p></td><td className="px-3 py-4">{c.paymentStatus || "—"}</td><td className="px-3 py-4 text-cyan-300">{c.followUpStatus}</td></tr>)}</tbody></table>{loading && <p className="py-8 text-center text-sm text-cyan-100/50">Loading CRM…</p>}{!loading && !page.content.length && <p className="py-8 text-center text-sm text-cyan-100/50">No customers match these filters.</p>}</div>
      <div className="mt-4 flex items-center justify-between"><p className="text-xs text-cyan-100/45">{page.totalElements} customers</p><div className="flex gap-2"><button aria-label="Previous page" disabled={!filters.page} onClick={()=>setFilters({...filters,page:filters.page-1})} className="rounded-xl border border-white/10 p-2 disabled:opacity-30"><ChevronLeft size={16}/></button><button aria-label="Next page" disabled={filters.page+1>=page.totalPages} onClick={()=>setFilters({...filters,page:filters.page+1})} className="rounded-xl border border-white/10 p-2 disabled:opacity-30"><ChevronRight size={16}/></button></div></div>
    </section></div>
}
